### ISSUE TITLE
Is it possible to mine India coin?

### ISSUE THREAD

**Issue by StiiCeva** [indiadev/india#1]
Is it possible to mine India coin? 

How can you mine it? On what is it based?  How much coin is it in circulation?

**Comment by MajjiR** [comment]
Yes, you can mine India coin.
Here's the pool: **stratum+tcp://lpool.name:3433** -u <WALLET_ADDRESS> -p c=INDIA
Use your India coin wallet address as username and "c=INDIA" as password.
Trade volume of India dropped to 60$/day, coinexchange.io is going to dump it anytime soon.
P.S I haven't tested that pool, it should work fine according to India coin team.
Happy mining!
